from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

CINEMATIC_STYLES = {
    "cine_letterbox": ASSStyleConfig(
        style_id="cine_letterbox",
        style_name="Cinematic Letterbox",
        category="cinematic",
        platform="generic",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        italic=True,
        border_style=1,
        outline=1.5,
        shadow=0.5,
        alignment=2,
        margin_v=160,
        spacing=2.0,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Classic cinematic italic with letterbox feel",
        tags=["letterbox", "cinematic", "italic", "film"],
    ),
    "cine_gold_warm": ASSStyleConfig(
        style_id="cine_gold_warm",
        style_name="Cinematic Gold Warm",
        category="cinematic",
        platform="generic",
        font_size=48,
        primary_colour="&H0000D7FF",
        outline_colour="&H00005C8A",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=2,
        alignment=2,
        margin_v=160,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Warm gold text for cinematic premium feel",
        tags=["gold", "warm", "premium", "luxury"],
    ),
    "cine_film_grain": ASSStyleConfig(
        style_id="cine_film_grain",
        style_name="Cinematic Film Grain",
        category="cinematic",
        platform="generic",
        font_size=46,
        primary_colour="&H00D0D0D0",
        outline_colour="&H00303030",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1,
        shadow=2.5,
        alignment=2,
        margin_v=160,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=700,
        font_map=dict(FULL_FONT_MAP),
        description="Desaturated text with grain-like shadow, film aesthetic",
        tags=["film", "grain", "desaturated", "vintage"],
    ),
    "cine_epic_center": ASSStyleConfig(
        style_id="cine_epic_center",
        style_name="Cinematic Epic Center",
        category="cinematic",
        platform="generic",
        font_size=64,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=3,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.SCALE_UP,
        animation_duration_ms=800,
        font_map=dict(FULL_FONT_MAP),
        description="Epic centered large text with dramatic scale-up",
        tags=["epic", "center", "large", "dramatic"],
    ),
    "cine_noir": ASSStyleConfig(
        style_id="cine_noir",
        style_name="Cinematic Noir",
        category="cinematic",
        platform="generic",
        font_size=44,
        primary_colour="&H00CCCCCC",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=0,
        shadow=3,
        alignment=2,
        margin_v=160,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Film noir style, muted text with deep shadow",
        tags=["noir", "dark", "muted", "shadow"],
    ),
    "cine_anamorphic": ASSStyleConfig(
        style_id="cine_anamorphic",
        style_name="Cinematic Anamorphic",
        category="cinematic",
        platform="generic",
        font_size=42,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=0.5,
        alignment=2,
        margin_v=160,
        scale_x=120,
        scale_y=85,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Stretched anamorphic look for widescreen feel",
        tags=["anamorphic", "widescreen", "stretched", "film"],
    ),
    "cine_subtitle_classic": ASSStyleConfig(
        style_id="cine_subtitle_classic",
        style_name="Cinematic Subtitle Classic",
        category="cinematic",
        platform="generic",
        font_size=42,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=1,
        alignment=2,
        margin_v=130,
        animation=ASSAnimationType.NONE,
        font_map=dict(FULL_FONT_MAP),
        description="Classic movie subtitle style, clean and readable",
        tags=["classic", "subtitle", "movie", "standard"],
    ),
    "cine_dramatic_fade": ASSStyleConfig(
        style_id="cine_dramatic_fade",
        style_name="Cinematic Dramatic Fade",
        category="cinematic",
        platform="generic",
        font_size=50,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        italic=True,
        border_style=1,
        outline=3,
        shadow=2,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=800,
        font_map=dict(FULL_FONT_MAP),
        description="Dramatic centered text with slow fade in and out",
        tags=["dramatic", "fade", "centered", "slow"],
    ),
}
