from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

CORPORATE_STYLES = {
    "corp_professional": ASSStyleConfig(
        style_id="corp_professional",
        style_name="Corporate Professional",
        category="corporate",
        platform="youtube",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=140,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Standard corporate subtitle, clean and professional",
        tags=["corporate", "professional", "standard", "clean"],
    ),
    "corp_dark_bar": ASSStyleConfig(
        style_id="corp_dark_bar",
        style_name="Corporate Dark Bar",
        category="corporate",
        platform="youtube",
        font_size=40,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HDD222222",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=140,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=250,
        font_map=dict(FULL_FONT_MAP),
        description="Dark bar background with white text, corporate feel",
        tags=["dark", "bar", "corporate", "subtitle"],
    ),
    "corp_blue_accent": ASSStyleConfig(
        style_id="corp_blue_accent",
        style_name="Corporate Blue Accent",
        category="corporate",
        platform="youtube",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFF0055A0",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=50,
        margin_r=50,
        margin_v=140,
        animation=ASSAnimationType.SLIDE_UP,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Corporate blue background bar with white text",
        tags=["blue", "accent", "bar", "brand"],
    ),
    "corp_key_message": ASSStyleConfig(
        style_id="corp_key_message",
        style_name="Corporate Key Message",
        category="corporate",
        platform="youtube",
        font_size=52,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Large centered key message, fades in and out",
        tags=["key", "message", "centered", "emphasis"],
    ),
    "corp_lower_third": ASSStyleConfig(
        style_id="corp_lower_third",
        style_name="Corporate Lower Third",
        category="corporate",
        platform="youtube",
        font_size=38,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HEE1A1A2E",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=1,
        margin_l=40,
        margin_v=130,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Corporate lower-third nameplate style",
        tags=["lower-third", "nameplate", "slide", "professional"],
    ),
    "corp_data_viz": ASSStyleConfig(
        style_id="corp_data_viz",
        style_name="Corporate Data Viz",
        category="corporate",
        platform="youtube",
        font_size=42,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H99000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=140,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Yellow data-value text on dark background",
        tags=["data", "viz", "yellow", "metric"],
    ),
    "corp_subtitle_neutral": ASSStyleConfig(
        style_id="corp_subtitle_neutral",
        style_name="Corporate Subtitle Neutral",
        category="corporate",
        platform="youtube",
        font_size=40,
        primary_colour="&H00EEEEEE",
        outline_colour="&H00222222",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=0.5,
        alignment=2,
        margin_v=130,
        animation=ASSAnimationType.NONE,
        font_map=dict(FULL_FONT_MAP),
        description="Neutral unobtrusive corporate subtitle",
        tags=["neutral", "subtitle", "unobtrusive", "clean"],
    ),
}
