from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

EDUCATION_STYLES = {
    "edu_clean_sans": ASSStyleConfig(
        style_id="edu_clean_sans",
        style_name="Education Clean Sans",
        category="education",
        platform="youtube",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Clean sans-serif for educational content",
        tags=["clean", "sans", "education", "readable"],
    ),
    "edu_keyword_green": ASSStyleConfig(
        style_id="edu_keyword_green",
        style_name="Education Keyword Green",
        category="education",
        platform="youtube",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        karaoke_highlight_colour="&H0000FF00",
        karaoke_highlight_outline="&H00008800",
        font_map=dict(FULL_FONT_MAP),
        description="White text with green keyword highlighting",
        tags=["keyword", "green", "highlight", "learning"],
    ),
    "edu_bullet_point": ASSStyleConfig(
        style_id="edu_bullet_point",
        style_name="Education Bullet Point",
        category="education",
        platform="youtube",
        font_size=40,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HCC000000",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=7,
        margin_l=60,
        margin_v=60,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Bullet-point style positioned top-left on dark background",
        tags=["bullet", "point", "slide", "structured"],
    ),
    "edu_typewriter_reveal": ASSStyleConfig(
        style_id="edu_typewriter_reveal",
        style_name="Education Typewriter Reveal",
        category="education",
        platform="youtube",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=0.5,
        alignment=2,
        margin_v=150,
        animation=ASSAnimationType.TYPEWRITER,
        animation_duration_ms=60,
        font_map=dict(FULL_FONT_MAP),
        description="Typewriter character reveal for teaching pacing",
        tags=["typewriter", "reveal", "pacing", "teaching"],
    ),
    "edu_formula_style": ASSStyleConfig(
        style_id="edu_formula_style",
        style_name="Education Formula",
        category="education",
        platform="youtube",
        font_size=50,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&HCC000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=5,
        margin_l=80,
        margin_r=80,
        margin_v=0,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Yellow formula style on dark background, centered",
        tags=["formula", "math", "yellow", "centered"],
    ),
    "edu_step_number": ASSStyleConfig(
        style_id="edu_step_number",
        style_name="Education Step Number",
        category="education",
        platform="youtube",
        font_size=42,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFF1E90FF",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=1,
        margin_l=50,
        margin_v=150,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Dodger blue bar with white text, step indicator",
        tags=["step", "number", "blue", "progress"],
    ),
    "edu_definition": ASSStyleConfig(
        style_id="edu_definition",
        style_name="Education Definition",
        category="education",
        platform="youtube",
        font_size=40,
        primary_colour="&H00FFD700",
        outline_colour="&H00000000",
        back_colour="&H99000000",
        bold=False,
        italic=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=70,
        margin_r=70,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        spacing=1.0,
        font_map=dict(FULL_FONT_MAP),
        description="Gold italic definition text on dark background",
        tags=["definition", "gold", "italic", "glossary"],
    ),
    "edu_code_block": ASSStyleConfig(
        style_id="edu_code_block",
        style_name="Education Code Block",
        category="education",
        platform="youtube",
        font_size=38,
        primary_colour="&H0000FF00",
        outline_colour="&H00000000",
        back_colour="&HFF1A1A1A",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=80,
        margin_r=80,
        margin_v=150,
        animation=ASSAnimationType.TYPEWRITER,
        animation_duration_ms=40,
        font_map=dict(FULL_FONT_MAP),
        description="Green monospace-style text on dark background, code feel",
        tags=["code", "green", "monospace", "programming"],
    ),
}
