from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

FASHION_STYLES = {
    "fashion_editorial": ASSStyleConfig(
        style_id="fashion_editorial",
        style_name="Fashion Editorial",
        category="fashion",
        platform="instagram",
        font_size=42,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1.5,
        shadow=0.5,
        alignment=2,
        margin_v=170,
        spacing=4.0,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Editorial serif-style with generous spacing",
        tags=["editorial", "serif", "spaced", "magazine"],
    ),
    "fashion_mono_chic": ASSStyleConfig(
        style_id="fashion_mono_chic",
        style_name="Fashion Mono Chic",
        category="fashion",
        platform="instagram",
        font_size=44,
        primary_colour="&H00CCCCCC",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=0,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        spacing=2.0,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=450,
        font_map=dict(FULL_FONT_MAP),
        description="Monochrome grey text, minimalist chic",
        tags=["mono", "grey", "chic", "minimalist"],
    ),
    "fashion_red_accent": ASSStyleConfig(
        style_id="fashion_red_accent",
        style_name="Fashion Red Accent",
        category="fashion",
        platform="instagram",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFFCC0000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="White text on red accent bar, bold fashion statement",
        tags=["red", "accent", "bar", "statement"],
    ),
    "fashion_luxury_gold": ASSStyleConfig(
        style_id="fashion_luxury_gold",
        style_name="Fashion Luxury Gold",
        category="fashion",
        platform="instagram",
        font_size=40,
        primary_colour="&H0000D7FF",
        outline_colour="&H008B6914",
        back_colour="&H99000000",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=70,
        margin_r=70,
        margin_v=170,
        spacing=3.0,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Gold text on dark background, luxury feel",
        tags=["luxury", "gold", "dark", "premium"],
    ),
    "fashion_minimalist": ASSStyleConfig(
        style_id="fashion_minimalist",
        style_name="Fashion Minimalist",
        category="fashion",
        platform="instagram",
        font_size=38,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=0,
        shadow=0,
        alignment=2,
        margin_v=170,
        spacing=1.0,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Ultra-minimalist white text, no effects",
        tags=["minimalist", "white", "ultra", "clean"],
    ),
    "fashion_high_contrast": ASSStyleConfig(
        style_id="fashion_high_contrast",
        style_name="Fashion High Contrast",
        category="fashion",
        platform="tiktok",
        font_size=50,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=250,
        font_map=dict(FULL_FONT_MAP),
        description="High contrast white on black outline, bold fashion",
        tags=["contrast", "bold", "black", "white"],
    ),
    "fashion_runway": ASSStyleConfig(
        style_id="fashion_runway",
        style_name="Fashion Runway",
        category="fashion",
        platform="instagram",
        font_size=48,
        primary_colour="&H00F5F5F5",
        outline_colour="&H00696969",
        back_colour="&H00000000",
        bold=False,
        italic=True,
        border_style=1,
        outline=1,
        shadow=3,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=700,
        font_map=dict(FULL_FONT_MAP),
        description="Centered italic runway title with slow fade",
        tags=["runway", "italic", "centered", "fade"],
    ),
}
