from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

FITNESS_STYLES = {
    "fitness_bold_energy": ASSStyleConfig(
        style_id="fitness_bold_energy",
        style_name="Fitness Bold Energy",
        category="fitness",
        platform="tiktok",
        font_size=56,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=200,
        scale_x=110,
        font_map=dict(FULL_FONT_MAP),
        description="Extra bold white text with energetic bounce",
        tags=["bold", "energy", "bounce", "white"],
    ),
    "fitness_neon_green": ASSStyleConfig(
        style_id="fitness_neon_green",
        style_name="Fitness Neon Green",
        category="fitness",
        platform="tiktok",
        font_size=52,
        primary_colour="&H0000FF00",
        outline_colour="&H00008800",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.GLOW_PULSE,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Neon green glow pulse for workout motivation",
        tags=["neon", "green", "glow", "workout"],
    ),
    "fitness_red_intensity": ASSStyleConfig(
        style_id="fitness_red_intensity",
        style_name="Fitness Red Intensity",
        category="fitness",
        platform="tiktok",
        font_size=54,
        primary_colour="&H000000FF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3.5,
        shadow=1.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.POP,
        animation_duration_ms=180,
        font_map=dict(FULL_FONT_MAP),
        description="Intense red text with pop animation",
        tags=["red", "intense", "pop", "power"],
    ),
    "fitness_countdown": ASSStyleConfig(
        style_id="fitness_countdown",
        style_name="Fitness Countdown",
        category="fitness",
        platform="tiktok",
        font_size=72,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=5,
        shadow=0,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.SCALE_UP,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Large centered countdown number with scale-up",
        tags=["countdown", "centered", "large", "timer"],
    ),
    "fitness_sport_blue": ASSStyleConfig(
        style_id="fitness_sport_blue",
        style_name="Fitness Sport Blue",
        category="fitness",
        platform="tiktok",
        font_size=48,
        primary_colour="&H00FF8000",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SLIDE_UP,
        animation_duration_ms=250,
        font_map=dict(FULL_FONT_MAP),
        description="Orange athletic text with fast slide-in",
        tags=["sport", "orange", "slide", "athletic"],
    ),
    "fitness_dark_power": ASSStyleConfig(
        style_id="fitness_dark_power",
        style_name="Fitness Dark Power",
        category="fitness",
        platform="tiktok",
        font_size=50,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HDD000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=40,
        margin_r=40,
        margin_v=180,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="White text on dark power bar background",
        tags=["dark", "power", "bar", "strength"],
    ),
    "fitness_hiit_flash": ASSStyleConfig(
        style_id="fitness_hiit_flash",
        style_name="Fitness HIIT Flash",
        category="fitness",
        platform="tiktok",
        font_size=58,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SHAKE,
        animation_duration_ms=100,
        font_map=dict(FULL_FONT_MAP),
        description="Flashing yellow shake text for HIIT intensity",
        tags=["hiit", "flash", "yellow", "shake"],
    ),
}
