from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

FOOD_STYLES = {
    "food_warm_orange": ASSStyleConfig(
        style_id="food_warm_orange",
        style_name="Food Warm Orange",
        category="food",
        platform="tiktok",
        font_size=48,
        primary_colour="&H0000A5FF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Warm orange text, appetizing and inviting",
        tags=["orange", "warm", "appetizing", "food"],
    ),
    "food_cream_dark": ASSStyleConfig(
        style_id="food_cream_dark",
        style_name="Food Cream Dark",
        category="food",
        platform="tiktok",
        font_size=44,
        primary_colour="&H00F5E6D3",
        outline_colour="&H005C4033",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Cream text on dark chocolate outline",
        tags=["cream", "chocolate", "warm", "dessert"],
    ),
    "food_recipe_step": ASSStyleConfig(
        style_id="food_recipe_step",
        style_name="Food Recipe Step",
        category="food",
        platform="youtube",
        font_size=40,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HDD8B4513",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=1,
        margin_l=50,
        margin_v=140,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Recipe step text on brown background bar",
        tags=["recipe", "step", "brown", "instruction"],
    ),
    "food_fresh_green": ASSStyleConfig(
        style_id="food_fresh_green",
        style_name="Food Fresh Green",
        category="food",
        platform="instagram",
        font_size=44,
        primary_colour="&H0032CD32",
        outline_colour="&H00006400",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Fresh lime green text, healthy and natural",
        tags=["green", "fresh", "healthy", "natural"],
    ),
    "food_spicy_red": ASSStyleConfig(
        style_id="food_spicy_red",
        style_name="Food Spicy Red",
        category="food",
        platform="tiktok",
        font_size=50,
        primary_colour="&H000000FF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=250,
        font_map=dict(FULL_FONT_MAP),
        description="Bold red spicy text with bounce animation",
        tags=["spicy", "red", "bold", "hot"],
    ),
    "food_golden_crisp": ASSStyleConfig(
        style_id="food_golden_crisp",
        style_name="Food Golden Crisp",
        category="food",
        platform="tiktok",
        font_size=46,
        primary_colour="&H0000D7FF",
        outline_colour="&H008B6914",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Golden text with dark brown outline, crispy feel",
        tags=["golden", "crisp", "brown", "fried"],
    ),
    "food_bubble_text": ASSStyleConfig(
        style_id="food_bubble_text",
        style_name="Food Bubble Text",
        category="food",
        platform="instagram",
        font_size=42,
        primary_colour="&H00222222",
        outline_colour="&H00000000",
        back_colour="&HCCFFF8DC",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=70,
        margin_r=70,
        margin_v=160,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Dark text on cornsilk bubble background",
        tags=["bubble", "cornsilk", "light", "cute"],
    ),
}
