from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

GAMING_STYLES = {
    "gaming_pixel": ASSStyleConfig(
        style_id="gaming_pixel",
        style_name="Gaming Pixel",
        category="gaming",
        platform="tiktok",
        font_size=48,
        primary_colour="&H0000FF00",
        outline_colour="&H00008800",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Green pixel-game style text",
        tags=["pixel", "green", "retro", "8-bit"],
    ),
    "gaming_rgb_split": ASSStyleConfig(
        style_id="gaming_rgb_split",
        style_name="Gaming RGB Split",
        category="gaming",
        platform="tiktok",
        font_size=52,
        primary_colour="&H00FF0000",
        outline_colour="&H000000FF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2,
        shadow=2,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SHAKE,
        animation_duration_ms=150,
        font_map=dict(FULL_FONT_MAP),
        description="RGB color split effect with red text and blue outline",
        tags=["rgb", "split", "glitch", "cyber"],
    ),
    "gaming_glitch": ASSStyleConfig(
        style_id="gaming_glitch",
        style_name="Gaming Glitch",
        category="gaming",
        platform="tiktok",
        font_size=50,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00FF00FF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SHAKE,
        animation_duration_ms=100,
        dialogue_overrides="\\blur0.5",
        font_map=dict(FULL_FONT_MAP),
        description="White text with magenta outline and glitch shake",
        tags=["glitch", "shake", "magenta", "cyber"],
    ),
    "gaming_neon_blue": ASSStyleConfig(
        style_id="gaming_neon_blue",
        style_name="Gaming Neon Blue",
        category="gaming",
        platform="tiktok",
        font_size=54,
        primary_colour="&H00FF8000",
        outline_colour="&H00005FFF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=3,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.GLOW_PULSE,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Orange text with blue neon glow pulse",
        tags=["neon", "blue", "orange", "pulse"],
    ),
    "gaming_speed_lines": ASSStyleConfig(
        style_id="gaming_speed_lines",
        style_name="Gaming Speed Lines",
        category="gaming",
        platform="tiktok",
        font_size=56,
        primary_colour="&H00FFFF00",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SLIDE_UP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Yellow speed text with fast slide-in",
        tags=["speed", "yellow", "fast", "slide"],
    ),
    "gaming_combo_counter": ASSStyleConfig(
        style_id="gaming_combo_counter",
        style_name="Gaming Combo Counter",
        category="gaming",
        platform="tiktok",
        font_size=60,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2,
        alignment=9,
        margin_l=50,
        margin_v=50,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=300,
        scale_x=110,
        scale_y=110,
        font_map=dict(FULL_FONT_MAP),
        description="Cyan combo counter positioned top-left, bouncy",
        tags=["combo", "counter", "cyan", "top"],
    ),
    "gaming_achievement": ASSStyleConfig(
        style_id="gaming_achievement",
        style_name="Gaming Achievement",
        category="gaming",
        platform="tiktok",
        font_size=44,
        primary_colour="&H00FFD700",
        outline_colour="&H008B6914",
        back_colour="&HCC000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=8,
        margin_l=40,
        margin_r=40,
        margin_v=50,
        animation=ASSAnimationType.SLIDE_DOWN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Gold achievement banner sliding down from top",
        tags=["achievement", "gold", "banner", "top"],
    ),
    "gaming_damage_number": ASSStyleConfig(
        style_id="gaming_damage_number",
        style_name="Gaming Damage Number",
        category="gaming",
        platform="tiktok",
        font_size=72,
        primary_colour="&H000000FF",
        outline_colour="&H00FFFFFF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.POP,
        animation_duration_ms=250,
        scale_x=120,
        scale_y=120,
        font_map=dict(FULL_FONT_MAP),
        description="Oversized red damage number centered with pop effect",
        tags=["damage", "number", "red", "pop"],
    ),
}
