from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

INSTAGRAM_STYLES = {
    "ig_minimal_white": ASSStyleConfig(
        style_id="ig_minimal_white",
        style_name="IG Minimal White",
        category="instagram",
        platform="instagram",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00333333",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1.5,
        shadow=0,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        spacing=2.0,
        font_map=dict(FULL_FONT_MAP),
        description="Clean minimal white text with thin outline, Instagram aesthetic",
        tags=["minimal", "clean", "aesthetic", "white"],
    ),
    "ig_serif_elegant": ASSStyleConfig(
        style_id="ig_serif_elegant",
        style_name="IG Serif Elegant",
        category="instagram",
        platform="instagram",
        font_size=46,
        primary_colour="&H00E8D5C4",
        outline_colour="&H004A3728",
        back_colour="&H00000000",
        bold=False,
        italic=True,
        border_style=1,
        outline=2,
        shadow=0.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=500,
        spacing=1.5,
        font_map=dict(FULL_FONT_MAP),
        description="Elegant serif italic with warm beige tones",
        tags=["serif", "elegant", "warm", "luxury"],
    ),
    "ig_pastel_pink": ASSStyleConfig(
        style_id="ig_pastel_pink",
        style_name="IG Pastel Pink",
        category="instagram",
        platform="instagram",
        font_size=48,
        primary_colour="&H00FFB6C1",
        outline_colour="&H008B4560",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Pastel pink bold text, soft and feminine",
        tags=["pastel", "pink", "soft", "feminine"],
    ),
    "ig_glassmorphism": ASSStyleConfig(
        style_id="ig_glassmorphism",
        style_name="IG Glassmorphism",
        category="instagram",
        platform="instagram",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H99000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=50,
        margin_r=50,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Glass-like frosted background with white text",
        tags=["glass", "frosted", "modern", "trendy"],
    ),
    "ig_soft_shadow": ASSStyleConfig(
        style_id="ig_soft_shadow",
        style_name="IG Soft Shadow",
        category="instagram",
        platform="instagram",
        font_size=50,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=0,
        shadow=4.0,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="White text with soft drop shadow, no outline",
        tags=["shadow", "soft", "clean", "modern"],
    ),
    "ig_cream_luxury": ASSStyleConfig(
        style_id="ig_cream_luxury",
        style_name="IG Cream Luxury",
        category="instagram",
        platform="instagram",
        font_size=42,
        primary_colour="&H00F5E6D3",
        outline_colour="&H008B7355",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        spacing=3.0,
        font_map=dict(FULL_FONT_MAP),
        description="Cream colored luxury text with wide spacing",
        tags=["luxury", "cream", "spaced", "premium"],
    ),
    "ig_typewriter": ASSStyleConfig(
        style_id="ig_typewriter",
        style_name="IG Typewriter",
        category="instagram",
        platform="instagram",
        font_size=40,
        primary_colour="&H00CCCCCC",
        outline_colour="&H00333333",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1,
        shadow=0,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.TYPEWRITER,
        animation_duration_ms=80,
        font_map=dict(FULL_FONT_MAP),
        description="Typewriter-style reveal effect, vintage feel",
        tags=["typewriter", "vintage", "reveal", "retro"],
    ),
    "ig_gradient_text": ASSStyleConfig(
        style_id="ig_gradient_text",
        style_name="IG Gradient Text",
        category="instagram",
        platform="instagram",
        font_size=52,
        primary_colour="&H00FF8C00",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        dialogue_overrides="\\1a&H40&\\3a&H20&",
        font_map=dict(FULL_FONT_MAP),
        description="Orange gradient text with transparency effect",
        tags=["gradient", "orange", "transparency", "warm"],
    ),
}
