from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

KIDS_STYLES = {
    "kids_bright_primary": ASSStyleConfig(
        style_id="kids_bright_primary",
        style_name="Kids Bright Primary",
        category="kids",
        platform="tiktok",
        font_size=50,
        primary_colour="&H000000FF",
        outline_colour="&H00FFFF00",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=300,
        scale_x=110,
        scale_y=110,
        font_map=dict(FULL_FONT_MAP),
        description="Bright red text with yellow outline, bouncy",
        tags=["red", "yellow", "bright", "bouncy"],
    ),
    "kids_rainbow_fun": ASSStyleConfig(
        style_id="kids_rainbow_fun",
        style_name="Kids Rainbow Fun",
        category="kids",
        platform="tiktok",
        font_size=48,
        primary_colour="&H00FF00FF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.RAINBOW,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Rainbow cycling magenta text, fun and colorful",
        tags=["rainbow", "fun", "colorful", "magical"],
    ),
    "kids_green_bubble": ASSStyleConfig(
        style_id="kids_green_bubble",
        style_name="Kids Green Bubble",
        category="kids",
        platform="tiktok",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HDD32CD32",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=170,
        animation=ASSAnimationType.POP,
        animation_duration_ms=250,
        font_map=dict(FULL_FONT_MAP),
        description="White text on green bubble background",
        tags=["green", "bubble", "pop", "cute"],
    ),
    "kids_candy_pink": ASSStyleConfig(
        style_id="kids_candy_pink",
        style_name="Kids Candy Pink",
        category="kids",
        platform="tiktok",
        font_size=46,
        primary_colour="&H00FF69B4",
        outline_colour="&H00FFFFFF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Candy pink text with white outline, sweet feel",
        tags=["candy", "pink", "sweet", "white"],
    ),
    "kids_ocean_blue": ASSStyleConfig(
        style_id="kids_ocean_blue",
        style_name="Kids Ocean Blue",
        category="kids",
        platform="tiktok",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HCC1E90FF",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="White text on ocean blue background",
        tags=["ocean", "blue", "water", "sea"],
    ),
    "kids_sunshine": ASSStyleConfig(
        style_id="kids_sunshine",
        style_name="Kids Sunshine",
        category="kids",
        platform="tiktok",
        font_size=50,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=2,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Bright yellow sunshine text with pop effect",
        tags=["sunshine", "yellow", "bright", "happy"],
    ),
    "kids_cartoon_pop": ASSStyleConfig(
        style_id="kids_cartoon_pop",
        style_name="Kids Cartoon Pop",
        category="kids",
        platform="tiktok",
        font_size=54,
        primary_colour="&H0000FF00",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3.5,
        shadow=0,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.POP,
        animation_duration_ms=180,
        scale_x=115,
        scale_y=115,
        font_map=dict(FULL_FONT_MAP),
        description="Oversized green cartoon text with pop",
        tags=["cartoon", "green", "pop", "oversized"],
    ),
}
