from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

MEME_COMEDY_STYLES = {
    "meme_impact": ASSStyleConfig(
        style_id="meme_impact",
        style_name="Meme Impact",
        category="meme_comedy",
        platform="tiktok",
        font_size=60,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=5,
        shadow=0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.POP,
        animation_duration_ms=150,
        scale_x=105,
        scale_y=105,
        font_map=dict(FULL_FONT_MAP),
        description="Classic Impact meme font, white on black outline",
        tags=["impact", "meme", "classic", "white"],
    ),
    "meme_white_on_black": ASSStyleConfig(
        style_id="meme_white_on_black",
        style_name="Meme White on Black",
        category="meme_comedy",
        platform="tiktok",
        font_size=52,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFF000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=30,
        margin_r=30,
        margin_v=180,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="White text on solid black bar, meme standard",
        tags=["white", "black", "bar", "standard"],
    ),
    "meme_shake_laugh": ASSStyleConfig(
        style_id="meme_shake_laugh",
        style_name="Meme Shake Laugh",
        category="meme_comedy",
        platform="tiktok",
        font_size=54,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SHAKE,
        animation_duration_ms=120,
        font_map=dict(FULL_FONT_MAP),
        description="Shaking yellow text for comedic emphasis",
        tags=["shake", "laugh", "yellow", "comedy"],
    ),
    "meme_rainbow": ASSStyleConfig(
        style_id="meme_rainbow",
        style_name="Meme Rainbow",
        category="meme_comedy",
        platform="tiktok",
        font_size=50,
        primary_colour="&H00FF0000",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.RAINBOW,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Rainbow cycling color text effect",
        tags=["rainbow", "color", "cycle", "fun"],
    ),
    "meme_comic_pop": ASSStyleConfig(
        style_id="meme_comic_pop",
        style_name="Meme Comic Pop",
        category="meme_comedy",
        platform="tiktok",
        font_size=58,
        primary_colour="&H000000FF",
        outline_colour="&H00FFFFFF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=2,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Red centered pop text for comic-style emphasis",
        tags=["comic", "pop", "red", "centered"],
    ),
    "meme_speech_text": ASSStyleConfig(
        style_id="meme_speech_text",
        style_name="Meme Speech Text",
        category="meme_comedy",
        platform="tiktok",
        font_size=42,
        primary_colour="&H00000000",
        outline_colour="&H00000000",
        back_colour="&HCCFFFFFF",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=80,
        margin_r=80,
        margin_v=160,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Black text on white bubble background",
        tags=["speech", "bubble", "white", "text"],
    ),
    "meme_uppercase_bold": ASSStyleConfig(
        style_id="meme_uppercase_bold",
        style_name="Meme Uppercase Bold",
        category="meme_comedy",
        platform="tiktok",
        font_size=56,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00444444",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=250,
        scale_x=108,
        font_map=dict(FULL_FONT_MAP),
        description="Extra bold uppercase with deep shadow",
        tags=["uppercase", "bold", "shadow", "strong"],
    ),
    "meme_drip_text": ASSStyleConfig(
        style_id="meme_drip_text",
        style_name="Meme Drip Text",
        category="meme_comedy",
        platform="tiktok",
        font_size=52,
        primary_colour="&H0000BFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=3.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Deep sky blue with extra long shadow drip effect",
        tags=["drip", "shadow", "blue", "trend"],
    ),
}
