from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

MUSIC_LYRICS_STYLES = {
    "music_karaoke_word": ASSStyleConfig(
        style_id="music_karaoke_word",
        style_name="Music Karaoke Word",
        category="music_lyrics",
        platform="tiktok",
        font_size=52,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.KARAOKE_WORD,
        karaoke_highlight_colour="&H0000FFFF",
        karaoke_highlight_outline="&H00008888",
        font_map=dict(FULL_FONT_MAP),
        description="Word-by-word karaoke highlight in cyan",
        tags=["karaoke", "word", "cyan", "sync"],
    ),
    "music_karaoke_char": ASSStyleConfig(
        style_id="music_karaoke_char",
        style_name="Music Karaoke Char",
        category="music_lyrics",
        platform="tiktok",
        font_size=50,
        primary_colour="&H00CCCCCC",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.KARAOKE_CHAR,
        karaoke_highlight_colour="&H0000FF00",
        karaoke_highlight_outline="&H00008800",
        karaoke_highlight_size=54,
        font_map=dict(FULL_FONT_MAP),
        description="Character-by-character karaoke in green, CJK optimized",
        tags=["karaoke", "char", "green", "cjk"],
    ),
    "music_fullscreen": ASSStyleConfig(
        style_id="music_fullscreen",
        style_name="Music Full Screen Lyrics",
        category="music_lyrics",
        platform="generic",
        font_size=56,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=2,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Full screen centered lyrics with fade transitions",
        tags=["fullscreen", "centered", "fade", "lyrics"],
    ),
    "music_rhythm_bounce": ASSStyleConfig(
        style_id="music_rhythm_bounce",
        style_name="Music Rhythm Bounce",
        category="music_lyrics",
        platform="tiktok",
        font_size=50,
        primary_colour="&H00FF69B4",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Pink bouncing text synced to rhythm",
        tags=["rhythm", "bounce", "pink", "beat"],
    ),
    "music_neon_sync": ASSStyleConfig(
        style_id="music_neon_sync",
        style_name="Music Neon Sync",
        category="music_lyrics",
        platform="tiktok",
        font_size=52,
        primary_colour="&H00FF00FF",
        outline_colour="&H008B008B",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=3,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.KARAOKE_WORD,
        karaoke_highlight_colour="&H0000FFFF",
        karaoke_highlight_outline="&H00008B8B",
        dialogue_overrides="\\blur0.8",
        font_map=dict(FULL_FONT_MAP),
        description="Neon magenta karaoke with cyan highlight sync",
        tags=["neon", "karaoke", "magenta", "sync"],
    ),
    "music_double_line": ASSStyleConfig(
        style_id="music_double_line",
        style_name="Music Double Line",
        category="music_lyrics",
        platform="generic",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HA0000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Two-line lyrics on dark bar, music video style",
        tags=["double-line", "bar", "lyrics", "music-video"],
    ),
    "music_glow_fade": ASSStyleConfig(
        style_id="music_glow_fade",
        style_name="Music Glow Fade",
        category="music_lyrics",
        platform="tiktok",
        font_size=48,
        primary_colour="&H00B0E0E6",
        outline_colour="&H00000080",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=3,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=700,
        font_map=dict(FULL_FONT_MAP),
        description="Soft powder blue with glow and slow fade",
        tags=["glow", "fade", "blue", "soft"],
    ),
    "music_rap_flow": ASSStyleConfig(
        style_id="music_rap_flow",
        style_name="Music Rap Flow",
        category="music_lyrics",
        platform="tiktok",
        font_size=54,
        primary_colour="&H00FFFF00",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.KARAOKE_WORD,
        karaoke_highlight_colour="&H0000FF00",
        font_map=dict(FULL_FONT_MAP),
        description="Rap flow style, yellow text with green word highlight",
        tags=["rap", "flow", "yellow", "fast"],
    ),
}
