from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

NEWS_STYLES = {
    "news_ticker": ASSStyleConfig(
        style_id="news_ticker",
        style_name="News Ticker",
        category="news",
        platform="youtube",
        font_size=36,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFFCC0000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=30,
        margin_r=30,
        margin_v=50,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Red breaking news ticker bar at top",
        tags=["ticker", "red", "breaking", "news"],
    ),
    "news_blue_bar": ASSStyleConfig(
        style_id="news_blue_bar",
        style_name="News Blue Bar",
        category="news",
        platform="youtube",
        font_size=40,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFF004488",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=40,
        margin_r=40,
        margin_v=140,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Dark blue bar with white text, news broadcast style",
        tags=["blue", "bar", "broadcast", "slide"],
    ),
    "news_condensed": ASSStyleConfig(
        style_id="news_condensed",
        style_name="News Condensed",
        category="news",
        platform="youtube",
        font_size=38,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=0.5,
        alignment=2,
        margin_v=130,
        scale_x=95,
        animation=ASSAnimationType.NONE,
        font_map=dict(FULL_FONT_MAP),
        description="Condensed news subtitle, no animation",
        tags=["condensed", "subtitle", "standard", "news"],
    ),
    "news_alert_red": ASSStyleConfig(
        style_id="news_alert_red",
        style_name="News Alert Red",
        category="news",
        platform="youtube",
        font_size=52,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3.5,
        shadow=0,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Large centered alert text, urgent breaking style",
        tags=["alert", "red", "urgent", "centered"],
    ),
    "news_lower_third": ASSStyleConfig(
        style_id="news_lower_third",
        style_name="News Lower Third",
        category="news",
        platform="youtube",
        font_size=38,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HDD333333",
        bold=False,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=1,
        margin_l=40,
        margin_v=120,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Grey lower-third bar for name/title info",
        tags=["lower-third", "grey", "name", "title"],
    ),
    "news_headline_gold": ASSStyleConfig(
        style_id="news_headline_gold",
        style_name="News Headline Gold",
        category="news",
        platform="youtube",
        font_size=48,
        primary_colour="&H0000D7FF",
        outline_colour="&H00000000",
        back_colour="&H99000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=140,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Gold headline on dark background, premium news",
        tags=["headline", "gold", "premium", "dark"],
    ),
    "news_clean_subtitle": ASSStyleConfig(
        style_id="news_clean_subtitle",
        style_name="News Clean Subtitle",
        category="news",
        platform="youtube",
        font_size=42,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=0.5,
        alignment=2,
        margin_v=130,
        animation=ASSAnimationType.NONE,
        font_map=dict(FULL_FONT_MAP),
        description="Clean white subtitle for news content",
        tags=["clean", "subtitle", "white", "standard"],
    ),
}
