from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

TIKTOK_STYLES = {
    "tiktok_neon_glow": ASSStyleConfig(
        style_id="tiktok_neon_glow",
        style_name="TikTok Neon Glow",
        category="tiktok",
        platform="tiktok",
        font_size=54,
        primary_colour="&H0000FFFF",
        outline_colour="&H00FF00FF",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3.5,
        shadow=2.0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=250,
        dialogue_overrides="\\blur1",
        font_map=dict(FULL_FONT_MAP),
        description="Neon cyan text with magenta outline and glow effect",
        tags=["neon", "glow", "vibrant", "night"],
    ),
    "tiktok_karaoke_pop": ASSStyleConfig(
        style_id="tiktok_karaoke_pop",
        style_name="TikTok Karaoke Pop",
        category="tiktok",
        platform="tiktok",
        font_size=52,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H80000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.KARAOKE_WORD,
        karaoke_highlight_colour="&H0000FF00",
        karaoke_highlight_outline="&H00008800",
        font_map=dict(FULL_FONT_MAP),
        description="Karaoke word-by-word highlight with green pop effect",
        tags=["karaoke", "word-by-word", "highlight"],
    ),
    "tiktok_bounce_bold": ASSStyleConfig(
        style_id="tiktok_bounce_bold",
        style_name="TikTok Bounce Bold",
        category="tiktok",
        platform="tiktok",
        font_size=56,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=0,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.BOUNCE,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Bold white text with bounce entrance animation",
        tags=["bounce", "bold", "energetic", "dynamic"],
    ),
    "tiktok_shake_alert": ASSStyleConfig(
        style_id="tiktok_shake_alert",
        style_name="TikTok Shake Alert",
        category="tiktok",
        platform="tiktok",
        font_size=52,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.SHAKE,
        animation_duration_ms=300,
        dialogue_overrides="\\bord4",
        font_map=dict(FULL_FONT_MAP),
        description="Shaking yellow text that grabs attention",
        tags=["shake", "alert", "attention", "viral"],
    ),
    "tiktok_pop_yellow": ASSStyleConfig(
        style_id="tiktok_pop_yellow",
        style_name="TikTok Pop Yellow",
        category="tiktok",
        platform="tiktok",
        font_size=58,
        primary_colour="&H0000FFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=4,
        shadow=2,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.POP,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Large yellow pop text, classic TikTok style",
        tags=["pop", "yellow", "classic", "tiktok"],
    ),
    "tiktok_gradient_bar": ASSStyleConfig(
        style_id="tiktok_gradient_bar",
        style_name="TikTok Gradient Bar",
        category="tiktok",
        platform="tiktok",
        font_size=48,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HA0000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=40,
        margin_r=40,
        margin_v=180,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="White text on semi-transparent black bar background",
        tags=["bar", "background", "clean", "overlay"],
    ),
    "tiktok_glow_pulse": ASSStyleConfig(
        style_id="tiktok_glow_pulse",
        style_name="TikTok Glow Pulse",
        category="tiktok",
        platform="tiktok",
        font_size=52,
        primary_colour="&H00FF80FF",
        outline_colour="&H00FF0080",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2.5,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.GLOW_PULSE,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Pink pulsing glow effect for energetic content",
        tags=["glow", "pulse", "pink", "energy"],
    ),
    "tiktok_uppercase_snap": ASSStyleConfig(
        style_id="tiktok_uppercase_snap",
        style_name="TikTok Uppercase Snap",
        category="tiktok",
        platform="tiktok",
        font_size=60,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00FF0000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1,
        alignment=2,
        margin_v=180,
        animation=ASSAnimationType.POP,
        animation_duration_ms=200,
        scale_x=110,
        scale_y=110,
        font_map=dict(FULL_FONT_MAP),
        description="Oversized uppercase snap text with red outline",
        tags=["uppercase", "snap", "impact", "bold"],
    ),
}
