from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

TRAVEL_STYLES = {
    "travel_adventure": ASSStyleConfig(
        style_id="travel_adventure",
        style_name="Travel Adventure",
        category="travel",
        platform="instagram",
        font_size=50,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=2,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        spacing=2.0,
        font_map=dict(FULL_FONT_MAP),
        description="Wide-spaced white text for adventure content",
        tags=["adventure", "wide", "spaced", "explore"],
    ),
    "travel_sunset_gold": ASSStyleConfig(
        style_id="travel_sunset_gold",
        style_name="Travel Sunset Gold",
        category="travel",
        platform="instagram",
        font_size=48,
        primary_colour="&H0000D7FF",
        outline_colour="&H008B6914",
        back_colour="&H00000000",
        bold=False,
        italic=True,
        border_style=1,
        outline=2,
        shadow=2,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Golden italic text for sunset travel vibes",
        tags=["sunset", "gold", "italic", "warm"],
    ),
    "travel_map_pin": ASSStyleConfig(
        style_id="travel_map_pin",
        style_name="Travel Map Pin",
        category="travel",
        platform="instagram",
        font_size=40,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HDDC0392B",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=1,
        margin_l=50,
        margin_v=140,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Location pin style on crimson background",
        tags=["map", "pin", "location", "crimson"],
    ),
    "travel_tropical": ASSStyleConfig(
        style_id="travel_tropical",
        style_name="Travel Tropical",
        category="travel",
        platform="tiktok",
        font_size=48,
        primary_colour="&H0000FFCC",
        outline_colour="&H00008060",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Tropical teal text with cyan-green outline",
        tags=["tropical", "teal", "cyan", "beach"],
    ),
    "travel_gradient_wide": ASSStyleConfig(
        style_id="travel_gradient_wide",
        style_name="Travel Gradient Wide",
        category="travel",
        platform="instagram",
        font_size=44,
        primary_colour="&H00FF8C00",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1.5,
        shadow=1,
        alignment=2,
        margin_v=170,
        spacing=3.0,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Orange text with extra-wide letter spacing",
        tags=["gradient", "wide", "spaced", "orange"],
    ),
    "travel_nature_green": ASSStyleConfig(
        style_id="travel_nature_green",
        style_name="Travel Nature Green",
        category="travel",
        platform="instagram",
        font_size=46,
        primary_colour="&H009ACD32",
        outline_colour="&H00556600",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Yellow-green nature-inspired text",
        tags=["nature", "green", "outdoor", "earth"],
    ),
    "travel_wanderlust": ASSStyleConfig(
        style_id="travel_wanderlust",
        style_name="Travel Wanderlust",
        category="travel",
        platform="instagram",
        font_size=46,
        primary_colour="&H00E6E6FA",
        outline_colour="&H008A2BE2",
        back_colour="&H00000000",
        bold=False,
        italic=True,
        border_style=1,
        outline=2,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=600,
        font_map=dict(FULL_FONT_MAP),
        description="Lavender italic with blue-violet outline, dreamy",
        tags=["wanderlust", "lavender", "dreamy", "italic"],
    ),
}
