from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

VLOG_STYLES = {
    "vlog_warm_casual": ASSStyleConfig(
        style_id="vlog_warm_casual",
        style_name="Vlog Warm Casual",
        category="vlog",
        platform="instagram",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00332222",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Warm casual white text with soft shadow",
        tags=["warm", "casual", "vlog", "soft"],
    ),
    "vlog_handwritten": ASSStyleConfig(
        style_id="vlog_handwritten",
        style_name="Vlog Handwritten",
        category="vlog",
        platform="instagram",
        font_size=44,
        primary_colour="&H00FFE4C4",
        outline_colour="&H008B7355",
        back_colour="&H00000000",
        bold=False,
        italic=True,
        border_style=1,
        outline=1.5,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Handwritten-feel beige italic text",
        tags=["handwritten", "italic", "beige", "personal"],
    ),
    "vlog_pastel_blue": ASSStyleConfig(
        style_id="vlog_pastel_blue",
        style_name="Vlog Pastel Blue",
        category="vlog",
        platform="instagram",
        font_size=44,
        primary_colour="&H00ADD8E6",
        outline_colour="&H005F9EA0",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Soft pastel blue with teal outline",
        tags=["pastel", "blue", "teal", "soft"],
    ),
    "vlog_sunset": ASSStyleConfig(
        style_id="vlog_sunset",
        style_name="Vlog Sunset",
        category="vlog",
        platform="instagram",
        font_size=48,
        primary_colour="&H00FF8C69",
        outline_colour="&H008B4513",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2,
        shadow=2,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Warm sunset salmon text with brown outline",
        tags=["sunset", "salmon", "warm", "romantic"],
    ),
    "vlog_minimal_grey": ASSStyleConfig(
        style_id="vlog_minimal_grey",
        style_name="Vlog Minimal Grey",
        category="vlog",
        platform="instagram",
        font_size=42,
        primary_colour="&H00CCCCCC",
        outline_colour="&H00333333",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1,
        shadow=0.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Minimal grey text, understated and clean",
        tags=["minimal", "grey", "understated", "clean"],
    ),
    "vlog_heart_accent": ASSStyleConfig(
        style_id="vlog_heart_accent",
        style_name="Vlog Heart Accent",
        category="vlog",
        platform="tiktok",
        font_size=46,
        primary_colour="&H00FF69B4",
        outline_colour="&H008B008B",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=2.5,
        shadow=1.5,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Soft pink text with dark pink outline, warm vlog feel",
        tags=["pink", "heart", "warm", "lifestyle"],
    ),
    "vlog_story_title": ASSStyleConfig(
        style_id="vlog_story_title",
        style_name="Vlog Story Title",
        category="vlog",
        platform="instagram",
        font_size=54,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=0,
        alignment=8,
        margin_v=80,
        animation=ASSAnimationType.SLIDE_DOWN,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Story title sliding in from top, vlog intro style",
        tags=["story", "title", "top", "intro"],
    ),
    "vlog_soft_green": ASSStyleConfig(
        style_id="vlog_soft_green",
        style_name="Vlog Soft Green",
        category="vlog",
        platform="instagram",
        font_size=44,
        primary_colour="&H0090EE90",
        outline_colour="&H002E8B57",
        back_colour="&H00000000",
        bold=False,
        border_style=1,
        outline=1.5,
        shadow=1,
        alignment=2,
        margin_v=170,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=350,
        font_map=dict(FULL_FONT_MAP),
        description="Soft light green text with sea green outline",
        tags=["green", "soft", "nature", "fresh"],
    ),
}
