from .base import FULL_FONT_MAP
from ..models import ASSStyleConfig, ASSAnimationType

YOUTUBE_STYLES = {
    "yt_professional": ASSStyleConfig(
        style_id="yt_professional",
        style_name="YouTube Professional",
        category="youtube",
        platform="youtube",
        font_size=48,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=3,
        shadow=1,
        alignment=2,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Clean professional white text with black outline",
        tags=["professional", "clean", "standard", "readable"],
    ),
    "yt_lower_third": ASSStyleConfig(
        style_id="yt_lower_third",
        style_name="YouTube Lower Third",
        category="youtube",
        platform="youtube",
        font_size=42,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HCC000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=1,
        margin_l=50,
        margin_v=150,
        animation=ASSAnimationType.SLIDE_LEFT,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Lower-third bar style, slides in from left",
        tags=["lower-third", "bar", "slide", "info"],
    ),
    "yt_dark_box": ASSStyleConfig(
        style_id="yt_dark_box",
        style_name="YouTube Dark Box",
        category="youtube",
        platform="youtube",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HE6000000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=60,
        margin_r=60,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN_OUT,
        animation_duration_ms=250,
        font_map=dict(FULL_FONT_MAP),
        description="Dark opaque box with centered white text",
        tags=["dark", "box", "centered", "readable"],
    ),
    "yt_chapter_mark": ASSStyleConfig(
        style_id="yt_chapter_mark",
        style_name="YouTube Chapter Mark",
        category="youtube",
        platform="youtube",
        font_size=40,
        primary_colour="&H00FFD700",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=7,
        margin_l=50,
        margin_v=50,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=500,
        font_map=dict(FULL_FONT_MAP),
        description="Gold chapter marker positioned top-left",
        tags=["chapter", "gold", "marker", "top"],
    ),
    "yt_speech_bubble": ASSStyleConfig(
        style_id="yt_speech_bubble",
        style_name="YouTube Speech Bubble",
        category="youtube",
        platform="youtube",
        font_size=40,
        primary_colour="&H00222222",
        outline_colour="&H00FFFFFF",
        back_colour="&HCCFFFFFF",
        bold=False,
        border_style=3,
        outline=2,
        shadow=0,
        alignment=2,
        margin_l=80,
        margin_r=80,
        margin_v=150,
        animation=ASSAnimationType.POP,
        animation_duration_ms=300,
        font_map=dict(FULL_FONT_MAP),
        description="Light speech bubble with dark text",
        tags=["speech", "bubble", "light", "comic"],
    ),
    "yt_highlight_bar": ASSStyleConfig(
        style_id="yt_highlight_bar",
        style_name="YouTube Highlight Bar",
        category="youtube",
        platform="youtube",
        font_size=44,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&HFFCC0000",
        bold=True,
        border_style=3,
        outline=0,
        shadow=0,
        alignment=2,
        margin_l=50,
        margin_r=50,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        font_map=dict(FULL_FONT_MAP),
        description="Red highlight bar background with white text",
        tags=["red", "highlight", "bar", "emphasis"],
    ),
    "yt_center_focus": ASSStyleConfig(
        style_id="yt_center_focus",
        style_name="YouTube Center Focus",
        category="youtube",
        platform="youtube",
        font_size=56,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=5,
        shadow=0,
        alignment=5,
        margin_v=0,
        animation=ASSAnimationType.SCALE_UP,
        animation_duration_ms=400,
        font_map=dict(FULL_FONT_MAP),
        description="Large centered text with thick outline, full focus",
        tags=["center", "large", "focus", "impact"],
    ),
    "yt_keyword_cyan": ASSStyleConfig(
        style_id="yt_keyword_cyan",
        style_name="YouTube Keyword Cyan",
        category="youtube",
        platform="youtube",
        font_size=46,
        primary_colour="&H00FFFFFF",
        outline_colour="&H00000000",
        back_colour="&H00000000",
        bold=True,
        border_style=1,
        outline=2.5,
        shadow=1,
        alignment=2,
        margin_v=150,
        animation=ASSAnimationType.FADE_IN,
        animation_duration_ms=200,
        karaoke_highlight_colour="&H00FFFF00",
        font_map=dict(FULL_FONT_MAP),
        description="White text with cyan keyword highlighting",
        tags=["keyword", "cyan", "highlight", "educational"],
    ),
}
